"""
One-time script to seed the Supabase 'products' table with the same product IDs
used in the frontend hardcoded catalog. This ensures FK constraints on order_items
and cart_items are satisfied when users place orders.

Run: python seed_products.py
"""

from app.database import supabase

PRODUCTS = [
    # ── KURTIS ──────────────────────────────────────────────────────────────────
    {
        "id": "kurti-floral-pink",
        "name": "Floral Printed Cotton Kurti",
        "category": "kurtis",
        "price": 899,
        "original_price": 1299,
        "rating": 4.8,
        "reviews_count": 312,
        "image_url": "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80",
        "colors": ["#E75480", "#FFFFFF", "#FFD700"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "tags": ["new", "best-seller"],
    },
    {
        "id": "kurti-block-print-blue",
        "name": "Block Print Straight Kurti",
        "category": "kurtis",
        "price": 1099,
        "original_price": 1599,
        "rating": 4.6,
        "reviews_count": 189,
        "image_url": "https://images.unsplash.com/photo-1583391733981-8498408ee4b6?w=800&auto=format&fit=crop&q=80",
        "colors": ["#1E3A5F", "#F5E6D3", "#8B4513"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "tags": ["new"],
    },
    {
        "id": "kurti-embroidered-green",
        "name": "Embroidered Anarkali Kurti",
        "category": "kurtis",
        "price": 1499,
        "original_price": 2199,
        "rating": 4.9,
        "reviews_count": 427,
        "image_url": "https://images.unsplash.com/photo-1594938298603-c8148c4b4d7e?w=800&auto=format&fit=crop&q=80",
        "colors": ["#2D5016", "#8B1A1A", "#1A237E"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["top", "featured"],
    },
    {
        "id": "kurti-mirror-work-orange",
        "name": "Mirror Work Festival Kurti",
        "category": "kurtis",
        "price": 1799,
        "original_price": 2499,
        "rating": 4.7,
        "reviews_count": 156,
        "image_url": "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=800&auto=format&fit=crop&q=80",
        "colors": ["#FF6B35", "#FFD700", "#8B1A1A"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "tags": ["new", "ethnic"],
    },
    {
        "id": "kurti-kalamkari-teal",
        "name": "Kalamkari Print Kurti",
        "category": "kurtis",
        "price": 1349,
        "original_price": 1899,
        "rating": 4.5,
        "reviews_count": 234,
        "image_url": "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&auto=format&fit=crop&q=80",
        "colors": ["#008080", "#8B4513", "#FFFFFF"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["new", "handicraft"],
    },

    # ── SAREES ──────────────────────────────────────────────────────────────────
    {
        "id": "saree-banarasi-red",
        "name": "Banarasi Silk Saree",
        "category": "saree",
        "price": 4999,
        "original_price": 6999,
        "rating": 4.9,
        "reviews_count": 534,
        "image_url": "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80",
        "colors": ["#8B0000", "#FFD700", "#006400"],
        "sizes": ["Free Size"],
        "tags": ["top", "premium"],
    },
    {
        "id": "saree-chanderi-blue",
        "name": "Chanderi Silk Cotton Saree",
        "category": "saree",
        "price": 2499,
        "original_price": 3499,
        "rating": 4.7,
        "reviews_count": 298,
        "image_url": "https://images.unsplash.com/photo-1583391733981-8498408ee4b6?w=800&auto=format&fit=crop&q=80",
        "colors": ["#1E3A5F", "#E6D5C3", "#2D5016"],
        "sizes": ["Free Size"],
        "tags": ["new", "elegant"],
    },
    {
        "id": "saree-maheshwari-violet",
        "name": "Maheshwari Handloom Saree",
        "category": "saree",
        "price": 3299,
        "original_price": 4599,
        "rating": 4.8,
        "reviews_count": 187,
        "image_url": "https://images.unsplash.com/photo-1594938298603-c8148c4b4d7e?w=800&auto=format&fit=crop&q=80",
        "colors": ["#6A0572", "#C0392B", "#FFD700"],
        "sizes": ["Free Size"],
        "tags": ["handloom", "vibrant"],
    },
    {
        "id": "saree-kanjivaram-gold",
        "name": "Kanjivaram Silk Saree",
        "category": "saree",
        "price": 7999,
        "original_price": 10999,
        "rating": 5.0,
        "reviews_count": 412,
        "image_url": "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80",
        "colors": ["#FFD700", "#8B0000", "#006400"],
        "sizes": ["Free Size"],
        "tags": ["top", "luxury"],
    },

    # ── LEHENGAS ────────────────────────────────────────────────────────────────
    {
        "id": "lehenga-bridal-pink",
        "name": "Bridal Embroidered Lehenga",
        "category": "lehenga",
        "price": 12999,
        "original_price": 18999,
        "rating": 5.0,
        "reviews_count": 87,
        "image_url": "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80",
        "colors": ["#FF69B4", "#FFD700", "#8B1A1A"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["top", "exclusive"],
    },
    {
        "id": "lehenga-navratri-multicolor",
        "name": "Navratri Chaniya Choli Set",
        "category": "lehenga",
        "price": 2999,
        "original_price": 4499,
        "rating": 4.8,
        "reviews_count": 342,
        "image_url": "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80",
        "colors": ["#FF6B35", "#9B59B6", "#27AE60"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "tags": ["new", "festive"],
    },
    {
        "id": "lehenga-floral-yellow",
        "name": "Floral Embroidery Lehenga",
        "category": "lehenga",
        "price": 5499,
        "original_price": 7999,
        "rating": 4.7,
        "reviews_count": 213,
        "image_url": "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80",
        "colors": ["#FFD700", "#FF69B4", "#008080"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["new", "modern"],
    },
    {
        "id": "lehenga-anarkali-blue",
        "name": "Anarkali Flared Lehenga Set",
        "category": "lehenga",
        "price": 8999,
        "original_price": 12999,
        "rating": 4.9,
        "reviews_count": 156,
        "image_url": "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80",
        "colors": ["#1E3A5F", "#8B0000", "#FFD700"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["top", "royal"],
    },

    # ── SALWAR SUITS ────────────────────────────────────────────────────────────
    {
        "id": "salwar-cotton-yellow",
        "name": "Cotton Linen Salwar Kameez",
        "category": "salwar",
        "price": 1299,
        "original_price": 1999,
        "rating": 4.5,
        "reviews_count": 211,
        "image_url": "https://images.unsplash.com/photo-1583391733981-8498408ee4b6?w=800&auto=format&fit=crop&q=80",
        "colors": ["#FFD700", "#FFFFFF", "#FF69B4"],
        "sizes": ["XS", "S", "M", "L", "XL", "XXL"],
        "tags": ["casual", "comfortable"],
    },
    {
        "id": "salwar-patiala-multicolor",
        "name": "Patiala Suit with Dupatta",
        "category": "salwar",
        "price": 1599,
        "original_price": 2199,
        "rating": 4.6,
        "reviews_count": 178,
        "image_url": "https://images.unsplash.com/photo-1594938298603-c8148c4b4d7e?w=800&auto=format&fit=crop&q=80",
        "colors": ["#9B59B6", "#E75480", "#27AE60"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["new", "traditional"],
    },
    {
        "id": "salwar-georgette-blue",
        "name": "Georgette Straight Salwar Suit",
        "category": "salwar",
        "price": 2199,
        "original_price": 2999,
        "rating": 4.7,
        "reviews_count": 143,
        "image_url": "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=800&auto=format&fit=crop&q=80",
        "colors": ["#1E3A5F", "#E75480", "#FFD700"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["semi-formal"],
    },

    # ── ANARKALIS ───────────────────────────────────────────────────────────────
    {
        "id": "anarkali-georgette-teal",
        "name": "Georgette Anarkali with Dupatta",
        "category": "anarkali",
        "price": 2299,
        "original_price": 3299,
        "rating": 4.8,
        "reviews_count": 264,
        "image_url": "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&auto=format&fit=crop&q=80",
        "colors": ["#008080", "#8B1A1A", "#1E3A5F"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["top", "elegant"],
    },
    {
        "id": "anarkali-silk-red",
        "name": "Heavy Silk Anarkali Suit",
        "category": "anarkali",
        "price": 3899,
        "original_price": 5499,
        "rating": 4.9,
        "reviews_count": 189,
        "image_url": "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80",
        "colors": ["#8B0000", "#FFD700", "#006400"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["top", "royal"],
    },

    # ── PASHTUNI POSHAK ─────────────────────────────────────────────────────────
    {
        "id": "pashtuni-traditional-blue",
        "name": "Traditional Pashtuni Dress",
        "category": "pashtuni",
        "price": 3499,
        "original_price": 4999,
        "rating": 4.9,
        "reviews_count": 98,
        "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Pashtun_woman_in_traditional_dress.jpg/800px-Pashtun_woman_in_traditional_dress.jpg",
        "colors": ["#1E3A5F", "#FFD700", "#8B0000"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["new", "cultural"],
    },
    {
        "id": "pashtuni-embroidered-black",
        "name": "Embroidered Pashtuni Kameez",
        "category": "pashtuni",
        "price": 4299,
        "original_price": 5999,
        "rating": 4.8,
        "reviews_count": 76,
        "image_url": "https://images.unsplash.com/photo-1583391733981-8498408ee4b6?w=800&auto=format&fit=crop&q=80",
        "colors": ["#111111", "#C0392B", "#FFD700"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["top", "heritage"],
    },
    {
        "id": "pashtuni-colorful-festive",
        "name": "Festive Pashtuni Poshak Set",
        "category": "pashtuni",
        "price": 5999,
        "original_price": 7999,
        "rating": 5.0,
        "reviews_count": 54,
        "image_url": "https://images.unsplash.com/photo-1594938298603-c8148c4b4d7e?w=800&auto=format&fit=crop&q=80",
        "colors": ["#FF6B35", "#9B59B6", "#FFD700"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["top", "celebration"],
    },

    # ── COTTON COLLECTION ───────────────────────────────────────────────────────
    {
        "id": "cotton-handloom-saree-blush",
        "name": "Handloom Pure Cotton Saree",
        "category": "cotton",
        "price": 1899,
        "original_price": 2599,
        "rating": 4.8,
        "reviews_count": 412,
        "image_url": "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80",
        "colors": ["#E8B4B8", "#FFFFFF", "#2D5016"],
        "sizes": ["Free Size"],
        "tags": ["new", "breathable"],
    },
    {
        "id": "cotton-block-print-kurti",
        "name": "Jaipuri Block Print Cotton Kurti",
        "category": "cotton",
        "price": 999,
        "original_price": 1499,
        "rating": 4.6,
        "reviews_count": 267,
        "image_url": "https://images.unsplash.com/photo-1583391733981-8498408ee4b6?w=800&auto=format&fit=crop&q=80",
        "colors": ["#1E3A5F", "#FFD700", "#C0392B"],
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "tags": ["daily-wear", "summer"],
    },
    {
        "id": "cotton-salwar-dupatta-set",
        "name": "Cotton Salwar with Chiffon Dupatta",
        "category": "cotton",
        "price": 2199,
        "original_price": 2999,
        "rating": 4.7,
        "reviews_count": 198,
        "image_url": "https://images.unsplash.com/photo-1594938298603-c8148c4b4d7e?w=800&auto=format&fit=crop&q=80",
        "colors": ["#9B59B6", "#FFFFFF", "#FF69B4"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["office", "comfort"],
    },
    {
        "id": "cotton-embroidered-anarkali",
        "name": "Embroidered Cotton Anarkali",
        "category": "cotton",
        "price": 2799,
        "original_price": 3799,
        "rating": 4.9,
        "reviews_count": 156,
        "image_url": "https://images.unsplash.com/photo-1585487000160-6ebcfceb0d03?w=800&auto=format&fit=crop&q=80",
        "colors": ["#FF6B35", "#FFD700", "#8B0000"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["festive", "featured"],
    },

    # ── LINEN COLLECTION ────────────────────────────────────────────────────────
    {
        "id": "linen-fusion-kurta-set",
        "name": "Linen Fusion Kurta with Palazzo",
        "category": "linen",
        "price": 2499,
        "original_price": 3299,
        "rating": 4.8,
        "reviews_count": 223,
        "image_url": "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&auto=format&fit=crop&q=80",
        "colors": ["#2F4F4F", "#F5F5DC", "#8B4513"],
        "sizes": ["S", "M", "L", "XL"],
        "tags": ["new", "minimal"],
    },
    {
        "id": "linen-saree-pastel",
        "name": "Pastel Linen Blend Saree",
        "category": "linen",
        "price": 3299,
        "original_price": 4499,
        "rating": 4.7,
        "reviews_count": 134,
        "image_url": "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800&auto=format&fit=crop&q=80",
        "colors": ["#B8C5D6", "#E8D5C4", "#6B7C8F"],
        "sizes": ["Free Size"],
        "tags": ["elegant", "lightweight"],
    },
    {
        "id": "linen-indo-western-coord",
        "name": "Linen Indo-Western Co-ord Set",
        "category": "linen",
        "price": 3999,
        "original_price": 5499,
        "rating": 4.9,
        "reviews_count": 89,
        "image_url": "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&auto=format&fit=crop&q=80",
        "colors": ["#36454F", "#FFD700", "#FFFFFF"],
        "sizes": ["XS", "S", "M", "L", "XL"],
        "tags": ["premium", "contemporary"],
    },
    {
        "id": "linen-dupatta-scarf-set",
        "name": "Handwoven Linen Dupatta Pair",
        "category": "linen",
        "price": 1299,
        "original_price": 1799,
        "rating": 4.5,
        "reviews_count": 312,
        "image_url": "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&auto=format&fit=crop&q=80",
        "colors": ["#D4C4A8", "#8B7355", "#F5F5DC"],
        "sizes": ["Free Size"],
        "tags": ["accessory", "layering"],
    },
]


def seed():
    print(f"Seeding {len(PRODUCTS)} products into Supabase ...")

    for product in PRODUCTS:
        pid = product["id"]
        # Check if already exists
        existing = supabase.table("products").select("id").eq("id", pid).execute()
        if existing.data:
            # Update existing product
            supabase.table("products").update(product).eq("id", pid).execute()
            print(f"  Updated: {pid}")
        else:
            supabase.table("products").insert(product).execute()
            print(f"  Inserted: {pid}")

    print("Done!")


if __name__ == "__main__":
    seed()
